version: '3.4'

services:
 poste:
   image: analogic/poste.io
   container_name: poste
   restart: always
   networks:
     - nginx
   ports:
     - "25:25"
     - "8000:80"
     - "4455:443"
     - "110:110" 
     - "143:143" 
     - "465:465" 
     - "587:587"
     - "993:993"
     - "995:995"
     - "4190:4190"
   environment:
     - HTTPS=ON
   volumes:
     - $path_mail_server:$path_mail_container
networks:
   nginx:
      external: 
         name: odoo_postgres
