version: '3.3'
services:
    db:
        image: $DB_IMAGE:$DB_VERSION
        container_name: db
        ports:
            - "5432:5432"
        environment:
            - POSTGRES_USER=$DB_USER
            - POSTGRES_PASSWORD=$DB_PASSWORD
            - POSTGRES_DB=postgres
        volumes:
            - $DB_LOCAL_PATH:$DB_CONTAINER_PATH
        networks:
            - postgres
    odoo:
        image: $ODOO_IMAGE:$ODOO_VERSION
        container_name: odoo
        depends_on:
            - db
        links:
            - db
        ports:
            - "8069:8069"
        volumes:
            - $CONF_LOCAL_PATH:$CONF_CONTAINER_PATH
            - $ADDONS_LOCAL_PATH:$ADDONS_CONTAINER_PATH
            - $CORE_LOCAL_PATH:$CORE_CONTAINER_PATH
        networks:
           - postgres
        command: odoo -i base
        environment:
            - DB_PORT_5432_TCP_ADDR=db
            - DB_PORT_5432_TCP_PORT=5432
            - DB_ENV_POSTGRES_USER=$DB_USER
            - DB_ENV_POSTGRES_PASSWORD=$DB_PASSWORD
            - DB_ENV_POSTGRES_DB=postgres
            - ADMIN_PASS=$ODOO_ADMIN_PASS
    pgadmin4:
        image: $PGADMIN_IMAGE:$PGADMIN_VERSION
        container_name: pgadmin4
        environment:
            - PGADMIN_DEFAULT_EMAIL=$PGADMIN_MAIL
            - PGADMIN_DEFAULT_PASSWORD=$PGADMIN_PASSWORD
        ports:
            - "5555:80"
        depends_on:
            - db
        links:
            - db
        networks:
            - postgres
        restart: unless-stopped
    wdb:
        image: kozea/wdb
        container_name: wdb
        ports:
            - "1984:1984"
    nginx: 
        image: nginx:1.15-alpine
        container_name: nginx
        volumes:
            - /opt/odoo/nginx:/etc/nginx/conf.d
            - /opt/odoo/certbot/conf:/etc/letsencrypt
            - /opt/odoo/certbot/www:/var/www/certbot
        command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
        depends_on:
            - odoo
        links:
            - odoo
        ports:
            - "80:80"
            - "443:443"
        networks:
            - postgres
    certbot:
        image: certbot/certbot
        container_name: certbot
        volumes:
           - /opt/odoo/certbot/conf:/etc/letsencrypt
           - /opt/odoo/certbot/www:/var/www/certbot
        entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    poste:
        image: analogic/poste.io
        container_name: poste
        restart: always
        networks:
           - postgres
        ports:
           - "25:25"
           - "8000:80"
           - "4455:443"
           - "110:110"
           - "143:143"
           - "465:465"
           - "587:587"
           - "993:993"
           - "995:995"
           - "4190:4190"
        environment:
           - HTTPS=ON
        volumes:
           - $PATH_MAIL_LOCAL:$PATH_MAIL_CONTAINER
networks:
     postgres:
       driver: bridge
